# Generated by Django 5.1.6 on 2025-03-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_piloto_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pilotos/'),
        ),
    ]
